name: 'obsession-calendar'
description: 'Transform HTML markup entries into a nift calendar and insert into a target file'
branding:
    icon: 'activity'
    color: 'green'
inputs:
  input:
    description: 'Input file'
    required: true
  target:
    description: 'Target file'
    required: true
runs:
    using: 'node16'
    main: 'index.js'
